name: Build Deb package

on:
  workflow_dispatch:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build-x86_64:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - name: Build Debian packages
        uses: jtdor/build-deb-action@v1.8.0
        with:
          # Name of a Docker image or path of a Dockerfile to use for the build container
          docker-image: debian:bookworm-slim
          # Extra packages to be installed as build dependencies
          extra-build-deps: dh-python dh-cmake
      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-x86_64
          path: debian/artifacts/*

  build-arm64:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64
      - name: Build Debian packages
        uses: jtdor/build-deb-action@v1.8.0
        with:
          # Name of a Docker image or path of a Dockerfile to use for the build container
          docker-image: debian:bookworm-slim
          # Extra packages to be installed as build dependencies
          extra-build-deps: dh-python dh-cmake
          extra-docker-args: --platform linux/arm64
      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-arm64
          path: debian/artifacts/*
